blank_issues_enabled: false
contact_links:
  - name: Code of Conduct concerns
    url: https://github.com/Forced-Alignment-and-Vowel-Extraction/.github/blob/main/CODE_OF_CONDUCT.md#enforcement
    about: To report concerns regarding the Code of Conduct, please email one of the contacts listed in the enforcement section.

